### ISSUE TITLE
Some Schemas Not Included in Scan in Metabase

### ISSUE THREAD

**Issue by digarcia78** [starburstdata/metabase-driver#138]
I am using the latest version of the driver, Metabase v0.52.1, and Trino v448. When executing the scan, some schemas are not being included. For example, the tmp schema appears when running the SHOW SCHEMAS command, but the driver never executes SHOW TABLES FROM tmp ....

Is this a known issue, or has it been reported before? Could there be a bug causing this behavior?

**Comment by lpoulain** [comment]
I was not able to reproduce this issue. Could you provide some details about the exact steps you followed inside Metabase to the issue you're seeing?

**Comment by digarcia78** [comment]
Thank you for looking into this. Here are the steps I followed:

    I navigated to the Database settings section in Metabase.
    I selected the connection for Starburst (v6.0.0), which uses Trino v448 and Metabase v0.52.6.
    In the database configuration, I clicked on the option to Synchronize database schema now.
    After the synchronization process completed, I went to the Table metadata section.
    In the tmp schema, I noticed that the new tables are not listed.

Please let me know if further details are needed!

**Comment by lpoulain** [comment]
@digarcia78 I cannot reproduce this issue. However, did you make sure that the schema is NOT set in your database configuration? If it is, Metabase will only scan tables in that schema.

**Comment by lpoulain** [comment]
@digarcia78 still cannot manage to reproduce the issue. Now, regarding the error when fetching metadata, do you see any error in the Trino/Starburst logs?

**Comment by lpoulain** [comment]
Also, what version of Trino/Starburst are you using?

**Comment by digarcia78** [comment]
I’ve checked the Trino logs, and I don’t see any errors related to fetching metadata. I’m using Trino version 448 (open-source).

Regarding compatibility, is this driver supported with Metabase versions v0.52.7 and v0.52.8?

**Comment by mithilajoshi** [comment]
I seem to be running into a similar issue. 

Metabase v52.6
Starburst driver: 6.0.0

Stack Trace: 

```
[ddf1a859-cc00-4ded-9053-fb37f02cfb20] 2025-01-28T14:50:49-08:00 FATAL metabase.driver.implementation.sync ERROR WITH QUERY  #error {
 :cause nil
 :via
 [{:type java.sql.SQLException
   :message Error executing query: null
   :at [io.trino.jdbc.TrinoStatement internalExecute TrinoStatement.java 287]}
  {:type io.trino.jdbc.$internal.guava.base.VerifyException
   :message nil
   :at [io.trino.jdbc.$internal.guava.base.Verify verify Verify.java 102]}]
 :trace
 [[io.trino.jdbc.$internal.guava.base.Verify verify Verify.java 102]
  [io.trino.jdbc.TrinoResultSet getColumns TrinoResultSet.java 313]
  [io.trino.jdbc.TrinoResultSet create TrinoResultSet.java 61]
  [io.trino.jdbc.TrinoStatement internalExecute TrinoStatement.java 262]
  [io.trino.jdbc.TrinoStatement execute TrinoStatement.java 240]
  [io.trino.jdbc.TrinoPreparedStatement executeQuery TrinoPreparedStatement.java 139]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery NewProxyPreparedStatement.java 743]
  [metabase.driver.implementation.sync$fn__120094 invokeStatic sync.clj 96]
  [metabase.driver.implementation.sync$fn__120094 invoke sync.clj 90]
  [clojure.lang.MultiFn invoke MultiFn.java 244]
  [metabase.driver.implementation.sync$describe_schema$fn__120098 invoke sync.clj 111]
  [clojure.core$filter$fn__5977$fn__5978 invoke core.clj 2822]
  [clojure.java.jdbc$init_reduce_rs invokeStatic jdbc.clj 1205]
  [clojure.java.jdbc$init_reduce_rs invoke jdbc.clj 1197]
  [clojure.java.jdbc$reducible_result_set_STAR_$reify__43028 reduce jdbc.clj 1227]
  [clojure.core$transduce invokeStatic core.clj 7025]
  [clojure.core$into invokeStatic core.clj 7042]
  [clojure.core$into invoke core.clj 7029]
  [metabase.driver.implementation.sync$describe_schema invokeStatic sync.clj 108]
  [metabase.driver.implementation.sync$describe_schema invoke sync.clj 102]
  [metabase.driver.implementation.sync$all_schemas$fn__120107 invoke sync.clj 126]
  [clojure.core$map$fn__5950$fn__5951 invoke core.clj 2759]
  [clojure.java.jdbc$init_reduce_rs invokeStatic jdbc.clj 1205]
  [clojure.java.jdbc$init_reduce_rs invoke jdbc.clj 1197]
  [clojure.java.jdbc$reducible_result_set_STAR_$reify__43028 reduce jdbc.clj 1227]
  [clojure.core$transduce invokeStatic core.clj 7025]
  [clojure.core$into invokeStatic core.clj 7042]
  [clojure.core$into invoke core.clj 7029]
  [metabase.driver.implementation.sync$all_schemas invokeStatic sync.clj 123]
  [metabase.driver.implementation.sync$all_schemas invoke sync.clj 117]
  [metabase.driver.implementation.sync$fn__120112$fn__120115 invoke sync.clj 137]
  [metabase.driver.implementation.execute$fn__120149$fn__120151 invoke execute.clj 71]
  [metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380 invokeStatic execute.clj 338]
  [metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380 invoke execute.clj 321]
  [metabase.driver.implementation.execute$fn__120149 invokeStatic execute.clj 50]
  [metabase.driver.implementation.execute$fn__120149 invoke execute.clj 48]
  [clojure.lang.MultiFn invoke MultiFn.java 244]
  [metabase.driver.implementation.sync$fn__120112 invokeStatic sync.clj 131]
  [metabase.driver.implementation.sync$fn__120112 invoke sync.clj 129]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [metabase.sync.fetch_metadata$db_metadata93299__93300 invokeStatic fetch_metadata.clj 30]
  [metabase.sync.fetch_metadata$db_metadata93299__93300 invoke fetch_metadata.clj 26]
  [metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015$fn__94016 invoke sync_metadata.clj 69]
  [metabase.sync.util$do_with_error_handling invokeStatic util.clj 191]
  [metabase.sync.util$do_with_error_handling invoke util.clj 184]
  [clojure.core$partial$fn__5929 invoke core.clj 2647]
  [metabase.driver$fn__59501 invokeStatic driver.clj 914]
  [metabase.driver$fn__59501 invoke driver.clj 914]
  [clojure.lang.MultiFn invoke MultiFn.java 239]
  [metabase.sync.util$sync_in_context$fn__63528 invoke util.clj 167]
  [metabase.sync.util$with_db_logging_disabled$fn__63525 invoke util.clj 159]
  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic util.clj 132]
  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke util.clj 126]
  [metabase.sync.util$with_start_and_finish_logging$fn__63512 invoke util.clj 144]
  [metabase.sync.util$with_sync_events63502__63503$fn__63507 invoke util.clj 118]
  [metabase.sync.util$with_duplicate_ops_prevented$fn__63492 invoke util.clj 90]
  [metabase.sync.util$do_sync_operation63543__63544 invokeStatic util.clj 216]
  [metabase.sync.util$do_sync_operation63543__63544 invoke util.clj 210]
  [metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015 invokeStatic sync_metadata.clj 68]
  [metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015 invoke sync_metadata.clj 65]
  [metabase.api.database$fn__106499$fn__106504 invoke database.clj 1017]
  [clojure.core$binding_conveyor_fn$fn__5842 invoke core.clj 2047]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 829]]}
[ddf1a859-cc00-4ded-9053-fb37f02cfb20] 2025-01-28T14:50:49-08:00 WARN metabase.sync.util Error in sync step Sync metadata for starburst Database 2 ''Trino'',java.sql.SQLException: ResultSet is closed,	at io.trino.jdbc.AbstractTrinoResultSet.checkOpen(AbstractTrinoResultSet.java:1852),	at io.trino.jdbc.AbstractTrinoResultSet.next(AbstractTrinoResultSet.java:210),	at io.trino.jdbc.TrinoResultSet.next(TrinoResultSet.java:45),	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:4511),	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1204),	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197),	at clojure.java.jdbc$reducible_result_set_STAR_$reify__43028.reduce(jdbc.clj:1227),	at clojure.core$transduce.invokeStatic(core.clj:7025),	at clojure.core$into.invokeStatic(core.clj:7042),	at clojure.core$into.invoke(core.clj:7029),	at metabase.driver.implementation.sync$describe_schema.invokeStatic(sync.clj:108),	at metabase.driver.implementation.sync$describe_schema.invoke(sync.clj:102),	at metabase.driver.implementation.sync$all_schemas$fn__120107.invoke(sync.clj:126),	at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759),	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205),	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197),	at clojure.java.jdbc$reducible_result_set_STAR_$reify__43028.reduce(jdbc.clj:1227),	at clojure.core$transduce.invokeStatic(core.clj:7025),	at clojure.core$into.invokeStatic(core.clj:7042),	at clojure.core$into.invoke(core.clj:7029),	at metabase.driver.implementation.sync$all_schemas.invokeStatic(sync.clj:123),	at metabase.driver.implementation.sync$all_schemas.invoke(sync.clj:117),	at metabase.driver.implementation.sync$fn__120112$fn__120115.invoke(sync.clj:137),	at metabase.driver.implementation.execute$fn__120149$fn__120151.invoke(execute.clj:71),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invokeStatic(execute.clj:338),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invoke(execute.clj:321),	at metabase.driver.implementation.execute$fn__120149.invokeStatic(execute.clj:50),	at metabase.driver.implementation.execute$fn__120149.invoke(execute.clj:48),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.implementation.sync$fn__120112.invokeStatic(sync.clj:131),	at metabase.driver.implementation.sync$fn__120112.invoke(sync.clj:129),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.sync.fetch_metadata$db_metadata93299__93300.invokeStatic(fetch_metadata.clj:30),	at metabase.sync.fetch_metadata$db_metadata93299__93300.invoke(fetch_metadata.clj:26),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015$fn__94016.invoke(sync_metadata.clj:69),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:191),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:184),	at clojure.core$partial$fn__5929.invoke(core.clj:2647),	at metabase.driver$fn__59501.invokeStatic(driver.clj:914),	at metabase.driver$fn__59501.invoke(driver.clj:914),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__63528.invoke(util.clj:167),	at metabase.sync.util$with_db_logging_disabled$fn__63525.invoke(util.clj:159),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126),	at metabase.sync.util$with_start_and_finish_logging$fn__63512.invoke(util.clj:144),	at metabase.sync.util$with_sync_events63502__63503$fn__63507.invoke(util.clj:118),	at metabase.sync.util$with_duplicate_ops_prevented$fn__63492.invoke(util.clj:90),	at metabase.sync.util$do_sync_operation63543__63544.invokeStatic(util.clj:216),	at metabase.sync.util$do_sync_operation63543__63544.invoke(util.clj:210),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invokeStatic(sync_metadata.clj:68),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invoke(sync_metadata.clj:65),	at metabase.api.database$fn__106499$fn__106504.invoke(database.clj:1017),	at clojure.core$binding_conveyor_fn$fn__5842.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628),	at java.base/java.lang.Thread.run(Thread.java:829)
[ddf1a859-cc00-4ded-9053-fb37f02cfb20] 2025-01-28T14:50:49-08:00 ERROR metabase.sync.fetch-metadata Error while fetching metdata with 'db-metadata',java.sql.SQLException: ResultSet is closed,	at io.trino.jdbc.AbstractTrinoResultSet.checkOpen(AbstractTrinoResultSet.java:1852),	at io.trino.jdbc.AbstractTrinoResultSet.next(AbstractTrinoResultSet.java:210),	at io.trino.jdbc.TrinoResultSet.next(TrinoResultSet.java:45),	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:4511),	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1204),	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197),	at clojure.java.jdbc$reducible_result_set_STAR_$reify__43028.reduce(jdbc.clj:1227),	at clojure.core$transduce.invokeStatic(core.clj:7025),	at clojure.core$into.invokeStatic(core.clj:7042),	at clojure.core$into.invoke(core.clj:7029),	at metabase.driver.implementation.sync$describe_schema.invokeStatic(sync.clj:108),	at metabase.driver.implementation.sync$describe_schema.invoke(sync.clj:102),	at metabase.driver.implementation.sync$all_schemas$fn__120107.invoke(sync.clj:126),	at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759),	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205),	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197),	at clojure.java.jdbc$reducible_result_set_STAR_$reify__43028.reduce(jdbc.clj:1227),	at clojure.core$transduce.invokeStatic(core.clj:7025),	at clojure.core$into.invokeStatic(core.clj:7042),	at clojure.core$into.invoke(core.clj:7029),	at metabase.driver.implementation.sync$all_schemas.invokeStatic(sync.clj:123),	at metabase.driver.implementation.sync$all_schemas.invoke(sync.clj:117),	at metabase.driver.implementation.sync$fn__120112$fn__120115.invoke(sync.clj:137),	at metabase.driver.implementation.execute$fn__120149$fn__120151.invoke(execute.clj:71),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invokeStatic(execute.clj:338),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invoke(execute.clj:321),	at metabase.driver.implementation.execute$fn__120149.invokeStatic(execute.clj:50),	at metabase.driver.implementation.execute$fn__120149.invoke(execute.clj:48),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.implementation.sync$fn__120112.invokeStatic(sync.clj:131),	at metabase.driver.implementation.sync$fn__120112.invoke(sync.clj:129),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.sync.fetch_metadata$db_metadata93299__93300.invokeStatic(fetch_metadata.clj:30),	at metabase.sync.fetch_metadata$db_metadata93299__93300.invoke(fetch_metadata.clj:26),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015$fn__94016.invoke(sync_metadata.clj:69),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:191),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:184),	at clojure.core$partial$fn__5929.invoke(core.clj:2647),	at metabase.driver$fn__59501.invokeStatic(driver.clj:914),	at metabase.driver$fn__59501.invoke(driver.clj:914),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__63528.invoke(util.clj:167),	at metabase.sync.util$with_db_logging_disabled$fn__63525.invoke(util.clj:159),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126),	at metabase.sync.util$with_start_and_finish_logging$fn__63512.invoke(util.clj:144),	at metabase.sync.util$with_sync_events63502__63503$fn__63507.invoke(util.clj:118),	at metabase.sync.util$with_duplicate_ops_prevented$fn__63492.invoke(util.clj:90),	at metabase.sync.util$do_sync_operation63543__63544.invokeStatic(util.clj:216),	at metabase.sync.util$do_sync_operation63543__63544.invoke(util.clj:210),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invokeStatic(sync_metadata.clj:68),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invoke(sync_metadata.clj:65),	at metabase.api.database$fn__106499$fn__106504.invoke(database.clj:1017),	at clojure.core$binding_conveyor_fn$fn__5842.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628),	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lpoulain** [comment]
The stack trace shows the error occurs inside the JDBC driver, as if there was a particular column it doesn't like. If you run the `EXECUTE IMMEDIATE 'SHOW TABLES FROM "tmp" LIKE ...'` command in the Trino CLI, does it succeed?

**Comment by mithilajoshi** [comment]
> The stack trace shows the error occurs inside the JDBC driver, as if there was a particular column it doesn't like. If you run the `EXECUTE IMMEDIATE 'SHOW TABLES FROM "tmp" LIKE ...'` command in the Trino CLI, does it succeed?

We don't have a "tmp" table in the hive schema, but executing a `SHOW TABLES FROM "prod" LIKE 'buy_%` works when it's issued against the trino cluster through DataGrip.

**Comment by digarcia78** [comment]
I tested with version 6.1.0, and the scan was successfully completed. Could it be that this version fixed something related to the scan?

**Comment by lpoulain** [comment]
The one thing it fixed is the abilities to run long queries (before that, after 3+ minutes Metabase would cancel the query)
