### ISSUE TITLE
Date Difference is not working

### ISSUE THREAD

**Issue by andrewdibiasio6** [starburstdata/metabase-driver#65]
When we use the [newly added](https://github.com/starburstdata/metabase-driver/pull/59) date diff xustom expression, we get an trino error trying to use AT TIME ZONE on a DATE data type which is not supported. 

Here is the query sent to trino:

```
-- Metabase:: userID: 1 queryType: MBQL queryHash: 4243acab790001d0d88dc444c8ae5a88f665cdd88d1157ea3836b820a8407964

SELECT

    "source"."orderkey" AS "orderkey",

    "source"."custkey" AS "custkey",

    "source"."orderstatus" AS "orderstatus",

    "source"."totalprice" AS "totalprice",

    "source"."orderdate" AS "orderdate",

    "source"."orderpriority" AS "orderpriority",

    "source"."clerk" AS "clerk",

    "source"."shippriority" AS "shippriority",

    "source"."comment" AS "comment",

    "source"."datetimeDiff" AS "datetimeDiff"

FROM

    (

        SELECT

            "sf1"."orders"."orderkey" AS "orderkey",

            "sf1"."orders"."custkey" AS "custkey",

            "sf1"."orders"."orderstatus" AS "orderstatus",

            "sf1"."orders"."totalprice" AS "totalprice",

            "sf1"."orders"."orderdate" AS "orderdate",

            "sf1"."orders"."orderpriority" AS "orderpriority",

            "sf1"."orders"."clerk" AS "clerk",

            "sf1"."orders"."shippriority" AS "shippriority",

            "sf1"."orders"."comment" AS "comment",

            date_diff(

                'day',

                date("sf1"."orders"."orderdate" AT TIME ZONE 'GMT'),

                date("sf1"."orders"."orderdate" AT TIME ZONE 'GMT')

            ) AS "datetimeDiff"

        FROM

            "sf1"."orders"

    ) "source"

LIMIT

    2000
```

`"sf1"."orders"."orderdate"` is a date type

error

```
io.trino.spi.TrinoException: line 1:809: Type of value must be a time or timestamp with or without time zone (actual varchar(20))
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitAtTimeZone(ExpressionAnalyzer.java:1968)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitAtTimeZone(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.AtTimeZone.accept(AtTimeZone.java:62)
	...
```

I think we can drop the casting [here](https://github.com/starburstdata/metabase-driver/pull/59/files#diff-9a67c16708c04be6b84a17323c47ab082680200da2aaa4643c5f3fdf79eebd8dR259-R260) 

See Trino's date interval functions: https://trino.io/docs/current/functions/datetime.html#interval-functions

Valid queries in Trino:
```
SELECT date_diff('hour', DATE '2020-02-29', TIMESTAMP '2020-03-01 02:00');

SELECT date_diff('hour', TIMESTAMP '2020-03-01', TIMESTAMP '2020-03-01 02:00');

SELECT date_diff('day', DATE '2020-02-29', DATE '2020-03-01');
```

## Success Criteria
* A new unit test is added to capture this issue for date
* Tests pass and manually testing passes as well.

**Comment by andrewdibiasio6** [comment]
This change solves the issue, but metabase tests start to fail

https://github.com/starburstdata/metabase-driver/commit/1c6c958717c046a37ea66d2ba9c236574b8d1454

**Comment by andrewdibiasio6** [comment]
New custom expression operation here: https://www.metabase.com/docs/latest/questions/query-builder/expressions/datetimediff

This seems to have only been tested with timestamp, but will fail with trino's date types. 

When working off main, you can reproduce the issue with: tpch/sf1/orders , using the orderDate field.


![Screenshot 2023-01-06 at 2 07 13 PM](https://user-images.githubusercontent.com/8988880/211082413-c749bd79-ec33-419d-80c7-9a5a74b2dd85.png)

![Screenshot 2023-01-06 at 2 07 20 PM](https://user-images.githubusercontent.com/8988880/211082426-049e7acd-c2d4-4e83-aa90-535aca7d53a4.png)
